'use client'

import type { Metadata } from "next";
import "./globals.css";
import { SpacemanThemeProvider } from '@space-man/react-theme-animation'

const metadata: Metadata = {
  title: "2048",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <SpacemanThemeProvider
          defaultTheme="system"
          defaultColorTheme="default"
          themes={['light', 'dark', 'system']}
          colorThemes={['default', 'supabase', 'mono']}
          // animationType="circle"
          duration={500}
        >
          {children}
        </SpacemanThemeProvider>
      </body>
    </html>
  );
}
